POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "jim",
  "password": "jim"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "jim",
  "password": "jim"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVlMmE4YzZhMGQ5ZDE2ZjA2MmVjZmIiLCJpYXQiOjE2NTAzMzg5NjN9.gmFXBujEDcblKLxEbrP9YJhSGv32g7fOXPebgrVaVCk

{
  "title": "test lan dau ",
  "description": "abc",
  "url": "react.com",
  "status": "TO LEARN"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVlMmE4YzZhMGQ5ZDE2ZjA2MmVjZmIiLCJpYXQiOjE2NTAzMzg5NjN9.gmFXBujEDcblKLxEbrP9YJhSGv32g7fOXPebgrVaVCk

###

PUT http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVlMmE4YzZhMGQ5ZDE2ZjA2MmVjZmIiLCJpYXQiOjE2NTAzMzg5NjN9.gmFXBujEDcblKLxEbrP9YJhSGv32g7fOXPebgrVaVCk

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVlMmE4YzZhMGQ5ZDE2ZjA2MmVjZmIiLCJpYXQiOjE2NTAzMzg5NjN9.gmFXBujEDcblKLxEbrP9YJhSGv32g7fOXPebgrVaVCk
